package autosar.ct.type;

public enum Nm_StateType {
	NM_STATE_UNINIT,
	NM_STATE_BUS_SLEEP,
	NM_STATE_PREPARE_BUS_SLEEP,
	NM_STATE_READY_SLEEP,
	NM_STATE_NORMAL_OPERATION,
	NM_STATE_REPEAT_MESSAGE,
	NM_STATE_SYNCHRONIZE
}
